chore: keep only one Dockerfile per Linux image variant (#1857)
* create new base images from jdk17 images

mkdir almalinux
git mv 11/almalinux/* almalinux
mkdir rhel
git mv 11/rhel/* rhel

for flavor in alpine debian rhel
do
    mkdir -p "${flavor}"
    git mv 17/"${flavor}"/* "${flavor}"
done

* remove previous jdk folders

// no jdk17, containing now only empty folders, invisible to git
for jdk in 11 21
do
    git rm -r "${jdk}"
done

* factorize Dockefiles

* shellcheck

* remove JLINK_COMPRESS

* cleaner version

* upstream changes

* more explicit switch

* add the same jdk21 jlink compress arg as Linux for Windows

* use a proper switch like Linux for Windows

* remove suppressed files reintroduced while incorporating upstream changes

* remove unneeded arm/v7 bypass of jlink

Ref:
- https://github.com/jenkinsci/docker/pull/1857/files\#r1584598652

* variable jlink arguments first

* variable jlink arguments first in Windows Dockerfile too

* fixup

* fixup rhel9

* fixup merge

* chore(deps): bump updatecli/updatecli-action from 2.56.0 to 2.57.0 (#1871)

* chore(deps): bump ubi9/ubi in /17/rhel/ubi9/hotspot (#1872)

---------

Co-authored-by: Mark Waite <mark.earl.waite@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/alpine/hotspot/Dockerfile b/alpine/hotspot/Dockerfile
--- a/alpine/hotspot/Dockerfile
+++ b/alpine/hotspot/Dockerfile
@@ -16,19 +16,26 @@ RUN apk add --no-cache \
     && rm -fr /var/cache/apk/* \
     && /usr/bin/jdk-download.sh alpine
 
-ENV PATH=/opt/jdk-${JAVA_VERSION}/bin:$PATH
+ENV PATH="/opt/jdk-${JAVA_VERSION}/bin:${PATH}"
 
 # Generate smaller java runtime without unneeded files
 # for now we include the full module path to maintain compatibility
 # while still saving space (approx 200mb from the full distribution)
-# Arguments to jlink are specific to Java 17 jlink
-RUN jlink \
-        --add-modules ALL-MODULE-PATH \
-        --strip-java-debug-attributes \
-        --no-man-pages \
-        --no-header-files \
-        --compress=2 \
-        --output /javaruntime
+RUN case "$(jlink --version 2>&1)" in \
+      # jlink version 11 has less features than JDK17+
+      "11."*) set -- "--strip-debug" "--compress=2" ;; \
+      "17."*) set -- "--strip-java-debug-attributes" "--compress=2" ;; \
+      # the compression argument is different for JDK21
+      "21."*) set -- "--strip-java-debug-attributes" "--compress=zip-6" ;; \
+      *) echo "ERROR: unmanaged jlink version pattern" && exit 1 ;; \
+    esac; \
+    jlink \
+      "$1" \
+      "$2" \
+      --add-modules ALL-MODULE-PATH \
+      --no-man-pages \
+      --no-header-files \
+      --output /javaruntime
 
 FROM alpine:"${ALPINE_TAG}" AS controller
 
diff --git a/rhel/ubi9/hotspot/Dockerfile b/rhel/ubi9/hotspot/Dockerfile
--- a/rhel/ubi9/hotspot/Dockerfile
+++ b/rhel/ubi9/hotspot/Dockerfile
@@ -1,56 +1,56 @@
-ARG ALPINE_TAG=3.19.1
+FROM registry.access.redhat.com/ubi9/ubi:9.4-947 as jre-build
 
-FROM alpine:"${ALPINE_TAG}" AS jre-build
+ARG JAVA_VERSION=17.0.11_9
 
-ARG JAVA_VERSION=21.0.3_9
-
-SHELL ["/bin/ash", "-o", "pipefail", "-c"]
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
 COPY jdk-download-url.sh /usr/bin/jdk-download-url.sh
 COPY jdk-download.sh /usr/bin/jdk-download.sh
-RUN apk add --no-cache \
+
+RUN dnf install --disableplugin=subscription-manager --setopt=install_weak_deps=0 --setopt=tsflags=nodocs --allowerasing -y \
     ca-certificates \
     curl \
     jq \
-    && rm -fr /var/cache/apk/* \
-    && /usr/bin/jdk-download.sh alpine
+    && dnf clean --disableplugin=subscription-manager all \
+    && /usr/bin/jdk-download.sh
 
-ENV PATH=/opt/jdk-${JAVA_VERSION}/bin:$PATH
+ENV PATH="/opt/jdk-${JAVA_VERSION}/bin:${PATH}"
 
 # Generate smaller java runtime without unneeded files
 # for now we include the full module path to maintain compatibility
 # while still saving space (approx 200mb from the full distribution)
-# Arguments to jlink are specific to Java 21 jlink
-RUN jlink \
-        --add-modules ALL-MODULE-PATH \
-        --strip-java-debug-attributes \
-        --no-man-pages \
-        --no-header-files \
-        --compress zip-6 \
-        --output /javaruntime
+RUN case "$(jlink --version 2>&1)" in \
+      # jlink version 11 has less features than JDK17+
+      "11."*) set -- "--strip-debug" "--compress=2" ;; \
+      "17."*) set -- "--strip-java-debug-attributes" "--compress=2" ;; \
+      # the compression argument is different for JDK21
+      "21."*) set -- "--strip-java-debug-attributes" "--compress=zip-6" ;; \
+      *) echo "ERROR: unmanaged jlink version pattern" && exit 1 ;; \
+    esac; \
+    jlink \
+      "$1" \
+      "$2" \
+      --add-modules ALL-MODULE-PATH \
+      --no-man-pages \
+      --no-header-files \
+      --output /javaruntime
 
-FROM alpine:"${ALPINE_TAG}" AS controller
-
-RUN apk add --no-cache \
-    bash \
-    coreutils \
-    curl \
-    git \
-    git-lfs \
-    gnupg \
-    musl-locales \
-    musl-locales-lang \
-    openssh-client \
-    tini \
-    ttf-dejavu \
-    tzdata \
-    unzip \
-  && git lfs install
+FROM registry.access.redhat.com/ubi9/ubi:9.4-947 AS controller
 
 ENV LANG C.UTF-8
 
 ARG TARGETARCH
 ARG COMMIT_SHA
+
+RUN dnf install --disableplugin=subscription-manager --setopt=install_weak_deps=0 --setopt=tsflags=nodocs -y \
+        fontconfig \
+        freetype \
+        git \
+        git-lfs \
+        unzip \
+        which \
+        tzdata \
+    && dnf clean --disableplugin=subscription-manager all
 
 ARG user=jenkins
 ARG group=jenkins
@@ -70,8 +70,8 @@ ENV REF $REF
 # ensure you use the same uid
 RUN mkdir -p $JENKINS_HOME \
   && chown ${uid}:${gid} $JENKINS_HOME \
-  && addgroup -g ${gid} ${group} \
-  && adduser -h "$JENKINS_HOME" -u ${uid} -G ${group} -s /bin/bash -D ${user}
+  && groupadd -g ${gid} ${group} \
+  && useradd -N -d "$JENKINS_HOME" -u ${uid} -g ${gid} -l -m -s /bin/bash ${user}
 
 # Jenkins home directory is a volume, so configuration and build history
 # can be persisted and survive image upgrades
@@ -81,6 +81,16 @@ VOLUME $JENKINS_HOME
 # to set on a fresh new installation. Use it to bundle additional plugins
 # or config file with your custom jenkins Docker image.
 RUN mkdir -p ${REF}/init.groovy.d
+
+# Use tini as subreaper in Docker container to adopt zombie processes
+ARG TINI_VERSION=v0.19.0
+COPY tini_pub.gpg "${JENKINS_HOME}/tini_pub.gpg"
+RUN curl -fsSL "https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static-${TARGETARCH}" -o /sbin/tini \
+  && curl -fsSL "https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static-${TARGETARCH}.asc" -o /sbin/tini.asc \
+  && gpg --no-tty --import "${JENKINS_HOME}/tini_pub.gpg" \
+  && gpg --verify /sbin/tini.asc \
+  && rm -rf /sbin/tini.asc /root/.gnupg \
+  && chmod +x /sbin/tini
 
 # jenkins version being bundled in this docker image
 ARG JENKINS_VERSION
